name: corn-p
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.2.6
  - r-base=3.6.2
  - r-broom=0.5.4
  - r-compositions=1.40_3
  - r-cowplot=1.0.0
  - r-ggmap=3.0.0
  - r-ggthemes=4.2.0
  - r-irkernel=1.1
  - r-mice=3.7.0
  - r-nlme=3.1_144
  - r-randomforest=4.6_14
  - r-tidyverse=1.3.0
  - r-vegan=2.5_6
  - r-vim=5.1.0
